spring:
  application:
    name: server
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    consumer:
      group-id: space-shield-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.spaceshield.server.kafka.event"

server:
  port: 8080

nasa:
  api-key: ${API_KEY}
  base-url: https://api.nasa.gov

kafka:
  topics:
    asteroids: space.asteroids
    solar: space.solar
    fireballs: space.fireballs
    risks: space.risks

logging:
  level:
    com.spaceshield: DEBUG
    org.springframework.kafka: INFO
