spring:
  application:
    name: server
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8080

nasa:
  api-key:  ${API_KEY}
  base-url: https://api.nasa.gov
